-
  hosts: all

  vars:
    http_port: 80
    dest: web
    git_name: portfolio-site
    user: bjoern

  remote_user: "{{ user }}"

  become: yes

  tasks:
  - name: clone git
    become_user: "{{ user }}"
    git:  repo="git@github.com:BFriedrichs/{{ git_name }}.git"
          dest="/home/{{ user }}/{{ dest }}/{{ git_name }}"
          accept_hostkey=yes
          force=yes

  - name: copy config
    copy: "src=config.yml dest=/home/{{ user }}/{{ dest }}/{{ git_name }}/config.yml owner={{ user }} group={{ user }} mode=0644"

  - name: install packages
    pip: "requirements=/home/{{ user }}/{{ dest }}/{{ git_name }}/requirements.txt"

  - name: minify
    command: python minify.py
    args:
      chdir: "/home/{{ user }}/{{ dest }}/{{ git_name }}"

  - name: serve site
    raw: "cd /home/{{ user }}/{{ dest }}/{{ git_name }}; nohup sudo python http.py -m -p 80 -l < /dev/null >/dev/null 2>&1 & sleep 1"
